events {}

http {
  server {
    listen 80;
    server_name service-a.local;

    location / {
      proxy_pass http://service-a:8080;
    }
  }

  server {
    listen 80;
    server_name service-b.local;

    location / {
      proxy_pass http://service-b:50051;
    }
  }
}
