// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';

export function Connect(arg1:main.ConnectionConfig):Promise<void>;

export function Disconnect():Promise<void>;

export function ExecuteQuery(arg1:string):Promise<db.QueryResult>;

export function IsConnected():Promise<boolean>;

export function ListDatabases():Promise<Array<string>>;

export function ListTables(arg1:string):Promise<Array<string>>;
