// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ListDatabases() {
  return window['go']['main']['App']['ListDatabases']();
}

export function ListTables(arg1) {
  return window['go']['main']['App']['ListTables'](arg1);
}
